version: '3.8'

services:
  ollama:
    image: ollama-api
    container_name: ollama
    ports:
      - "127.0.0.1:11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - ollama-network

  api:
    build: .
    container_name: ollama-api
    ports:
      - "5001:5001"
    environment:
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - ollama
    networks:
      - ollama-network

networks:
  ollama-network:
    driver: bridge

volumes:
  ollama_data:
